### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by geniusgogo** [pannzh/Airkiss#1]
$ make clean ;make
rm -f  airkiss main.o osdep.o linux.o radiotap/radiotap-parser.o common.o wifi_scan.o airkiss.o
gcc  main.c -o main.o
In file included from main.c:4:0:
wifi_scan.h:4:27: fatal error: netlink/errno.h: 没有那个文件或目录
 #include <netlink/errno.h>
                           ^
compilation terminated.
make: **\* [main.o] 错误 1

host:ubuntu server 14.04.3

**Comment by evilpan** [comment]
```
locate netlink/errno.h
```

看是否有这个文件,如果没有表示netlink没安装:

```
sudo apt-get install libnl-3-dev libnl-genl-3-dev
```

**Comment by geniusgogo** [comment]
谢谢，是库的路径没修改。

**Comment by w450434204** [comment]
netlink已经安装了还是报错。请问库的路径怎么修改。谢谢啦

**Comment by w450434204** [comment]
编译报错:wifi_scan.h:4:27: fatal error: netlink/errno.h: 没有那个文件或目录

locate netlink/errno.h  执行这个命令没有输出结果。

然后执行这个命令sudo apt-get install libnl-3-dev libnl-genl-3-dev，提示系统已安装。不需要更新。

不知道怎么处理了，楼上有人说是库的路径要修改。不知道怎么更改，困扰几天了，希望楼主能帮忙看一下啊。谢谢！
