### ISSUE TITLE
移植问题

### ISSUE THREAD

**Issue by w450434204** [pannzh/Airkiss#11]
你好，我想将这些代码交叉编译到固件端使用。交叉编译时libnl库 是不是包含libnl-genl-3库，两个库都需要交叉编码吗？

**Comment by evilpan** [comment]
你并不需要移植所有的程序。airkiss只是一个独立于硬件平台的应用层协议。如果你运行的是现代的实时操作系统，那么对应系统一般会有编译好的wifi芯片驱动，你可以通过CLI或者SDK去获得对应接口;如果是定制的嵌入式系统，或者没有操作系统，那也还是需要wifi芯片提供对应的驱动，或者提供代码然后自己交叉编译到对应处理器架构上。 一般来说，wifi芯片的驱动应该包括一些封装的接口（函数），如ap/station模式切换，扫描热点，连接热点等。利用这些接口获得的数据再经过airkiss的处理，即可实现和demo类似的简单上层了。 在2016年12月20日 17:05 ，w450434204写道： 你好，我想将这些代码交叉编译到固件端使用。交叉编译时libnl库 是不是包含libnl-genl-3库，两个库都需要交叉编码吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by w450434204** [comment]
谢谢你，我正在一步步移植，交叉编译第三方库和工具。我的开发板是安卓系统，在执行ioctl(SIOCSIWMODE) failed: Invalid argument时候报错，不知道什么原因。希望能得到你的指教。

root@86v_hd:/data # ./airkiss wlan0                                            
80211 driver_id is 17
index is 56
NL80211_CMD_TRIGGER_SCAN sent 36 bytes to the kernel.
Waiting for scan to complete...
Got NL80211_CMD_NEW_SCAN_RESULTS.
Scan is done.
NL80211_CMD_GET_SCAN sent 28 bytes to the kernel.
Mac Address:[24:05:0f:58:a1:c5], Channel:[ 1], SSID_CRC:[94], SSID:[jsf]
Mac Address:[24:69:68:0b:e0:5d], Channel:[ 1], SSID_CRC:[fd], SSID:[Abellstar]
Mac Address:[b8:a3:86:aa:eb:72], Channel:[ 7], SSID_CRC:[64], SSID:[dlink]
Mac Address:[28:cf:e9:0c:6d:49], Channel:[11], SSID_CRC:[50], SSID:[呵呵]
Mac Address:[24:05:0f:8b:1c:50], Channel:[11], SSID_CRC:[ 3], SSID:[360]
Mac Address:[20:a6:80:44:f2:36], Channel:[ 7], SSID_CRC:[eb], SSID:[HUAWEI-B315-F236]
Mac Address:[00:36:76:59:91:2b], Channel:[11], SSID_CRC:[95], SSID:[123]
Mac Address:[b0:d5:9d:31:48:de], Channel:[ 6], SSID_CRC:[68], SSID:[Eleheat]
Mac Address:[2c:f0:a2:f3:8e:5c], Channel:[11], SSID_CRC:[13], SSID:[Mac mini--yanjun]
Mac Address:[b0:d5:9d:46:e3:5b], Channel:[ 6], SSID_CRC:[ 0], SSID:[]
Mac Address:[00:87:46:13:e9:f0], Channel:[ 6], SSID_CRC:[63], SSID:[360免费WiFi-F0]
Mac Address:[fc:d7:33:bf:18:40], Channel:[ 6], SSID_CRC:[32], SSID:[south-star]
Mac Address:[50:bd:5f:24:a1:3d], Channel:[11], SSID_CRC:[26], SSID:[SOUTHSTAR_VIP]
ioctl(SIOCSIWMODE) failed: Invalid argument

ARP linktype is set to 1 (Ethernet) - expected ARPHRD_IEEE80211,
ARPHRD_IEEE80211_FULL or ARPHRD_IEEE80211_PRISM instead.  Make
sure RFMON is enabled: run 'airmon-ng start wlan0 <#>'
Sysfs injection support was not found either.

cannot init interface wlan0

**Comment by w450434204** [comment]
大神在吗？有空帮我解答下吧 在线等。

**Comment by evilpan** [comment]
可否手动将网卡置于混杂模式？ iwconfig wlan0 mode monitor up 在2016年12月22日 11:48 ，w450434204写道： 谢谢你，我正在一步步移植，交叉编译第三方库和工具。我的开发板是安卓系统，在执行ioctl(SIOCSIWMODE) failed: Invalid argument时候报错，不知道什么原因。希望能得到你的指教。
 root@86v_hd:/data # ./airkiss wlan0 80211 driver_id is 17 index is 56 NL80211_CMD_TRIGGER_SCAN sent 36 bytes to the kernel. Waiting for scan to complete... Got NL80211_CMD_NEW_SCAN_RESULTS. Scan is done. NL80211_CMD_GET_SCAN sent 28 bytes to the kernel. Mac Address:[24:05:0f:58:a1:c5], Channel:[ 1], SSID_CRC:[94], SSID:[jsf] Mac Address:[24:69:68:0b:e0:5d], Channel:[ 1], SSID_CRC:[fd], SSID:[Abellstar] Mac Address:[b8:a3:86:aa:eb:72], Channel:[ 7], SSID_CRC:[64], SSID:[dlink] Mac Address:[28:cf:e9:0c:6d:49], Channel:[11], SSID_CRC:[50], SSID:[呵呵] Mac Address:[24:05:0f:8b:1c:50], Channel:[11], SSID_CRC:[ 3], SSID:[360] Mac Address:[20:a6:80:44:f2:36], Channel:[ 7], SSID_CRC:[eb], SSID:[HUAWEI-B315-F236] Mac Address:[00:36:76:59:91:2b], Channel:[11], SSID_CRC:[95], SSID:[123] Mac Address:[b0:d5:9d:31:48:de], Channel:[ 6], SSID_CRC:[68], SSID:[Eleheat] Mac Address:[2c:f0:a2:f3:8e:5c], Channel:[11], SSID_CRC:[13], SSID:[Mac mini--yanjun] Mac Address:[b0:d5:9d:46:e3:5b], Channel:[ 6], SSID_CRC:[ 0], SSID:[] Mac Address:[00:87:46:13:e9:f0], Channel:[ 6], SSID_CRC:[63], SSID:[360免费WiFi-F0] Mac Address:[fc:d7:33:bf:18:40], Channel:[ 6], SSID_CRC:[32], SSID:[south-star] Mac Address:[50:bd:5f:24:a1:3d], Channel:[11], SSID_CRC:[26], SSID:[SOUTHSTAR_VIP] ioctl(SIOCSIWMODE) failed: Invalid argument ARP linktype is set to 1 (Ethernet) - expected ARPHRD_IEEE80211, ARPHRD_IEEE80211_FULL or ARPHRD_IEEE80211_PRISM instead. Make sure RFMON is enabled: run 'airmon-ng start wlan0 <#>' Sysfs injection support was not found either. cannot init interface wlan0 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by w450434204** [comment]
谢谢你一路的帮忙，之前是不可以手动设置为混杂模式，现在我将Wi-Fi网卡驱动程序升级了，可以实现一键配置的功能了。

**Comment by w450434204** [comment]
现在还有一个小问题：就是wifi驱动程序升级后，预扫描工作总是报错，具体的运行如下。不知道是什么原因，你知道这是什么原因吗？有空帮我解答下，谢谢啦。
**1|root@86v_hd:/ # ./data/airkiss wlan0**                                         
80211 driver_id is 17
index is 5
NL80211_CMD_TRIGGER_SCAN sent 36 bytes to the kernel.
Waiting for scan to complete...
**error_handler() called.
WARNING: err has a value of -19.
ERROR: nl_recvmsgs() returned -31 (No such device).
do_scan_trigger() failed with -31.
ERROR to scan AP, init with all 13 channels**
air_cfg size:116
Airkiss version: V1.2
airkiss_recv_discover success
base len:76
Lock channel in 5
airkiss_process_magic_code success
total_len:23, ssid crc:fd
airkiss_process_prefix_code success
pswd_len:13, pswd_lencrc:fd, need seq:4, seq map:f
seq:1, 61,6f,31,32
now seq map:2
seq:0, 77,75,62,69
now seq map:3
seq:1, 61,32,27,47
CRC check error, invalid sequence, Discared it.
seq:1, 61,6f,31,32
now seq map:3
seq:3, 2e,65,6c,6c
CRC check error, invalid sequence, Discared it.
seq:2, 33,34,24,27
now seq map:7
seq:2, 24,27,2e,41
CRC check error, invalid sequence, Discared it.
seq:4, 65,6c,6c,73
now seq map:7
seq:0, 77,75,62,69
now seq map:7
seq:4, 65,6c,6c,73
now seq map:7
seq:0, 77,62,69,61
CRC check error, invalid sequence, Discared it.
seq:2, 33,34,24,27
now seq map:7
seq:2, 33,34,24,27
now seq map:7
seq:2, 33,34,24,27
now seq map:7
seq:0, 77,75,62,69
now seq map:7
seq:0, 77,75,62,69
now seq map:7
seq:4, 65,6c,74,72
CRC check error, invalid sequence, Discared it.
seq:4, 65,6c,6c,73
CRC check error, invalid sequence, Discared it.
seq:2, 33,34,24,27
now seq map:7
seq:3, 2e,47,41,62
now seq map:f
User data is :0x77, 0x75, 0x62, 0x69, 0x61, 0x6f, 0x31, 0x32, 0x33, 0x34, 0x24, 0x27, 0x2e, 0x47, 0x41, 0x62, 0x 0, 0x 0, 0x 0, 0x 0, 0x 0, 0x 0, 0x 0, 0x 0, Airkiss completed.
get result: ssid_crc:fd
key:wubiao1234$'.
key_len:13
random:71
Sending random to broadcast..

**Comment by w450434204** [comment]
你对接受数据进行了优化，由于我现在不准备预扫描信道。准备接受全部数据，为什么最后一个序列总是接受不到？？？？？大神有空帮我分析下原因，谢谢啦，很着急。。。
我将源代码中的
 // only receive password and random
        air_cfg->need_seq = ((air_cfg->pswd_len + 1) + 3)/4; 
更改为
       air_cfg->need_seq = ((air_cfg->total_len) + 3)/4; 
 得到如下打印信息：
wubiao@wubiao-Rev-1-0:~/下载/Airkiss-master (2)$ sudo ./airkiss wlp5s0
80211 driver_id is 26
index is 3
NL80211_CMD_TRIGGER_SCAN sent 36 bytes to the kernel.
Waiting for scan to complete...
Got NL80211_CMD_NEW_SCAN_RESULTS.
Scan is done.
NL80211_CMD_GET_SCAN sent 28 bytes to the kernel.
Mac Address:[24:69:68:0b:e0:5d], Channel:[ 1], SSID_CRC:[fd], SSID:[Abellstar]
Mac Address:[b8:a3:86:aa:eb:72], Channel:[ 7], SSID_CRC:[64], SSID:[dlink]
Mac Address:[b0:d5:9d:31:48:de], Channel:[11], SSID_CRC:[68], SSID:[Eleheat]
Mac Address:[28:cf:e9:0c:6d:49], Channel:[11], SSID_CRC:[50], SSID:[呵呵]
Mac Address:[2c:f0:a2:f3:8e:5c], Channel:[11], SSID_CRC:[13], SSID:[Mac mini--yanjun]
Mac Address:[20:a6:80:44:f2:36], Channel:[ 5], SSID_CRC:[eb], SSID:[HUAWEI-B315-F236]
Mac Address:[fc:d7:33:bf:18:40], Channel:[ 6], SSID_CRC:[32], SSID:[south-star]
down iface wlp5s0
set iface wlp5s0 type to monitor
up iface wlp5s0
air_cfg size:128
Airkiss version: V1.2
exec cmd: iw wlp5s0 set channel 7
exec cmd: iw wlp5s0 set channel 11
exec cmd: iw wlp5s0 set channel 5
exec cmd: iw wlp5s0 set channel 6
scan all channels
exec cmd: iw wlp5s0 set channel 1
exec cmd: iw wlp5s0 set channel 7
exec cmd: iw wlp5s0 set channel 11
exec cmd: iw wlp5s0 set channel 5
exec cmd: iw wlp5s0 set channel 6
scan all channels
exec cmd: iw wlp5s0 set channel 1
exec cmd: iw wlp5s0 set channel 7
exec cmd: iw wlp5s0 set channel 11
exec cmd: iw wlp5s0 set channel 5
exec cmd: iw wlp5s0 set channel 6
scan all channels
exec cmd: iw wlp5s0 set channel 1
airkiss_recv_discover success
base len:76
Lock channel in 1
airkiss_process_magic_code success
total_len:18, ssid crc:fd
airkiss_process_prefix_code success
**pswd_len:8, pswd_lencrc:c2, need seq:5, seq map:1f**
seq:0, 31,32,33,34
now seq map:1
seq:2, 13,41,62,65
now seq map:5
seq:3, 6c,6c,73,74
now seq map:d
seq:2, 13,41,62,65
now seq map:d
seq:3, 6c,6c,73,74
now seq map:d
seq:0, 31,32,33,34
now seq map:d
seq:1, 35,36,37,38
now seq map:f
seq:2, 13,41,62,65
now seq map:f
seq:3, 6c,6c,73,74
now seq map:f
seq:0, 31,32,33,34
now seq map:f
seq:2, 13,41,62,65
**now seq map:f**
seq:3, 6c,6c,73,74
now seq map:f
seq:2, 13,41,62,65
now seq map:f
seq:3, 6c,6c,73,74
now seq map:f
seq:0, 31,32,33,34
now seq map:f
seq:1, 35,36,37,38
now seq map:f
seq:2, 13,41,62,65
now seq map:f
seq:3, 6c,6c,73,74
now seq map:f
seq:0, 31,32,33,34
now seq map:f
seq:1, 35,36,37,38
now seq map:f
seq:2, 13,41,62,65
now seq map:f
seq:3, 6c,6c,73,74
now seq map:f
seq:0, 31,32,33,34
now seq map:f
seq:1, 35,36,37,38
now seq map:f
seq:3, 6c,6c,73,74
now seq map:f
seq:1, 35,36,37,38
now seq map:f

**Comment by evilpan** [comment]
你好,扫描信道的代码由于用到默认的网卡驱动因此可能对部分外接网卡不适用,这部分我正在调整中,预计两三天内就可以把代码更新上来.

**Comment by evilpan** [comment]
@w450434204 经过测试发现微信并没有按照流出的文档那样发送全部的essid,而是在最后一个sequence里尽可能的补上essid的前几个字节,因此如果要完整获得essid信息,必须进行预扫描部分,具体可以参考之前的commit:
https://github.com/pannzh/Airkiss/commit/62a2f68297fb5ba073573d6ba49e0818aaf80879

**Comment by w450434204** [comment]
wubiao@wubiao-Rev-1-0:~/桌面/Airkiss-master$ make
gcc -c -g -Wall -Wno-unused-but-set-variable main.c -o main.o
In file included from main.c:12:0:
**utils/wifi_scan.h:4:19: fatal error: iwlib.h: 没有那个文件或目录**
compilation terminated.
 
报告这个错误，是因为系统没有Wireless Tools动态库，安装一下就可以了。 现在又报以下错误，
wubiao@wubiao-Rev-1-0:~/桌面/Airkiss-master$ make clean
rm -f  airkiss main.o capture/common.o capture/osdep.o capture/linux.o capture/radiotap/radiotap-parser.o utils/wifi_scan.o airkiss.o
wubiao@wubiao-Rev-1-0:~/桌面/Airkiss-master$ make
gcc -c -g -Wall -Wno-unused-but-set-variable main.c -o main.o
gcc -c -g -Wall -Wno-unused-but-set-variable capture/common.c -o capture/common.o
gcc -c -g -Wall -Wno-unused-but-set-variable capture/osdep.c -o capture/osdep.o
gcc -c -g -Wall -Wno-unused-but-set-variable capture/linux.c -o capture/linux.o
capture/linux.c: In function ‘openraw’:
capture/linux.c:1295:63: warning: comparison of constant ‘6’ with boolean expression is always false [-Wbool-compare]
         if (set_monitor( dev, iface, fd ) && !dev->drivertype == DT_ORINOCO )
                                                               ^
capture/linux.c:1295:63: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
capture/linux.c:1305:67: warning: comparison of constant ‘6’ with boolean expression is always false [-Wbool-compare]
             if (set_monitor( dev, iface, fd ) && !dev->drivertype == DT_ORINOCO
                                                                   ^
capture/linux.c:1305:67: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
gcc -c -g -Wall -Wno-unused-but-set-variable capture/radiotap/radiotap-parser.c -o capture/radiotap/radiotap-parser.o
gcc -c -g -Wall -Wno-unused-but-set-variable utils/wifi_scan.c -o utils/wifi_scan.o
gcc -c -g -Wall -Wno-unused-but-set-variable airkiss.c -o airkiss.o
gcc main.o capture/common.o capture/osdep.o capture/linux.o capture/radiotap/radiotap-parser.o utils/wifi_scan.o airkiss.o -o airkiss -liw -lrt 
**/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiw.so：对‘ceil’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiw.so：对‘trunc’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiw.so：对‘pow’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiw.so：对‘log10’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiw.so：对‘floor’未定义的引用**
collect2: error: ld returned 1 exit status
Makefile:16: recipe for target 'airkiss' failed
make: *** [airkiss] Error 1

**Comment by w450434204** [comment]
已经解决，这是缺少库的依赖，添加-lm即可解决。供他人参考吧。
