### ISSUE TITLE
W-iFi芯片如何连接指定网络？

### ISSUE THREAD

**Issue by w450434204** [pannzh/Airkiss#13]
大神，请教一个问题。设备端接受到Wi-Fi数据信息后，怎么通过相应的命令控制Wi-Fi芯片去连接指定的网络？是通过wpa_supplicant工具来实现吗？还是通过iw dev wlan0 connect [网络 SSID] key 0:[WEP 密钥]等命令操作。

**Comment by w450434204** [comment]
大神，后续会对控制WiFi配置网络，进行代码补充吗？

**Comment by evilpan** [comment]
Linux系统下,可以参考:
https://unix.stackexchange.com/questions/283722/how-to-connect-to-wifi-from-command-line

简而言之,可以通过以下任一命令:
1) wpa_supplicant
2) nm_cli
3) wpa_cli

来进行wifi的连接, 如果是DHCP方式, 再通过dhclient命令来获取动态分配的IP地址.
