### ISSUE TITLE
scan failure

### ISSUE THREAD

**Issue by geniusgogo** [pannzh/Airkiss#2]
Waiting for scan to complete...
**# **error_handler() called.
WARNING: err has a value of -19.
ERROR: nl_recvmsgs() returned -31 (No such device).
do_scan_trigger() failed with -31**.**

host:openwrt 14.07

**Comment by geniusgogo** [comment]
其实扫描和读写wifi数据用pcap就应该可以的了吧？我怀疑我这平台上nl库有问题。
在我的openwrt上pcap可以完成你nl上的所有功能。

**Comment by evilpan** [comment]
no such device, 我用的是wlan1,你要看看你的无线网卡名字是什么(wlanX). 另外pcap只能抓取普通socket数据, 底层通常需要通过kernel接口, 如果是嵌入式设备则用wifi模块提供的驱动接口.

**Comment by geniusgogo** [comment]
我已经用pcap做了实验可以解析出数据，只是你的filter和我用pcap抓到的数据包格式不一致。
我可能需要自己去解析pcap抓到的数据包格式来做解析。

非常感谢！

**Comment by evilpan** [comment]
已经将wifi_scan的部分进行优化.
