### ISSUE TITLE
SSID的CRC相同

### ISSUE THREAD

**Issue by geniusgogo** [pannzh/Airkiss#3]
测试发现SSID的CRC可能存在相同的情况，这种情况有什么好的办法加以区分？

**Comment by evilpan** [comment]
airkiss流程中会发送SSID只不过为了节约时间我没去读取.若周围ap过多导致ssidCRC相同你可以选择完整读取SSID,;
另外也可以在reverse字段保存下AP的MAC地址,这样可以保证不会连接错.

**Comment by evilpan** [comment]
@geniusgogo 一般来说crc相同是因为周围有相同名字的热点, 这种情况下这些热点都是互相组网的. 如果一定要连接某个特定热点, 可以通过802.11头里面的bssid字段来进行区分.
