### ISSUE TITLE
这个怎么使用啊

### ISSUE THREAD

**Issue by w450434204** [pannzh/Airkiss#5]
这个是编程库，然后以第三方库的形式放在客户端的代码里面吗？我是小白，正在了解AirKiss技术。求大神指导。

**Comment by evilpan** [comment]
不了解的可以先用一下微信官方的Airkiss静态库, 这个项目只是Airkiss的一种可能的实现.

**Comment by w450434204** [comment]
我的Linux内核版本号是Linux version 3.5.0-51-generic。编译时候报这个错。求解答，在线等。谢谢啦
ys01->make
gcc -c -g -I/usr/local/include/libnl3 main.c -o main.o
In file included from main.c:4:0:
wifi_scan.h:4:27: fatal error: netlink/errno.h: No such file or directory
compilation terminated.

**Comment by evilpan** [comment]
参考[issue #1 ](https://github.com/pannzh/Airkiss/issues/1)

**Comment by w450434204** [comment]
大神。真心求指教啊。这代码是不是放在固件端(开发板)烧成库,然后运行它。我现在想在虚拟机的Linux系统下面可以测试吗？我最近刚入门以前是做客户端开发的。现在项目要实现智能设备配置。我的QQ是450434204如果方便可以指教下我。谢谢

**Comment by w450434204** [comment]
我的意思是。要使用你这套代码。是不是买一套Esp8266开发板工具？

**Comment by evilpan** [comment]
Airkiss 只是应用层面处理数据的一种方法,和平台无关,唯一的要求是支持802.11. 只不过这里测试airkiss的demo是linux下的, 用到抓包的一些库要在linux下安装.

在自己的项目中要集成airkiss的话,你只需要airkiss.c 和 airkiss.h就可以了

**Comment by w450434204** [comment]
编译报错:wifi_scan.h:4:27: fatal error: netlink/errno.h: 没有那个文件或目录

locate netlink/errno.h  执行这个命令没有输出结果。

然后执行这个命令sudo apt-get install libnl-3-dev libnl-genl-3-dev，提示系统已安装。不需要更新。

不知道怎么处理了，楼上有人说是库的路径要修改。不知道怎么更改，困扰几天了，希望楼主能帮忙看一下啊。谢谢！

**Comment by w450434204** [comment]
刚才那个问题解决了。现在报这个错:
ys01->sudo ./airkiss eth0
ioctl(SIOCSIWMODE) failed: Operation not supported

ARP linktype is set to 1 (Ethernet) - expected ARPHRD_IEEE80211,
ARPHRD_IEEE80211_FULL or ARPHRD_IEEE80211_PRISM instead.  Make
sure RFMON is enabled: run 'airmon-ng start eth0 <#>'
Sysfs injection support was not found either.

cannot init interface eth0

**Comment by evilpan** [comment]
airkiss需要支持802.11的**无线网卡** ,eth0是有线网口,显然是不行的.

**Comment by w450434204** [comment]
嗯。谢谢，虚拟机下面不能使用笔记本内置的无线网卡。我现在将笔记本做成双系统，再安装一个Linux系统，我的笔记本无线网卡是支持混杂模式的。。
