### ISSUE TITLE
客户端程序问题

### ISSUE THREAD

**Issue by w450434204** [pannzh/Airkiss#6]
非常感谢你的帮助。请问您有开发客户端程序吗？只能使用微信客户端进行调试吗？

**Comment by w450434204** [comment]
大神，这程序有配套的客户端程序吗？(不使用微信客户端的测试)，我想结合客户端程序，学习下。谢谢解答

**Comment by evilpan** [comment]
微信客户端,airkissdebugger,以及github上有人自己实现的[手机客户端](https://github.com/zhchbin/WeChatAirKiss),都是可用的客户端程序

**Comment by w450434204** [comment]
嗯嗯 我现在正在认真的看你的源代码。有一点疑问: ssid部分不从data字段读取而只取其crc(用reserved字段记录), 上层应用将记录的ssid/crc进行对比,则可以获取目标的ssid信息并连接.连接后根据airkiss协议, 向10000端口广播random值通知发送端即可完成配置.
我的SSID中不包含中文,终端打印的SSID信息都是0x 0 0x 0 0x 0;我想看下我当前接受到密码的SSID，将你的这行注释代码打开会报错。    //wifi_scan(wifi_if, &scan_callback);我的目的就是想在打印信息中看到SSID的信息。 可以做到吗？谢谢你了
