### ISSUE TITLE
关于优化问题。

### ISSUE THREAD

**Issue by w450434204** [pannzh/Airkiss#7]
经过认真看你的代码。这段打印被你注释了吧。你的注释信息说:airkiss上层在抓包之前先扫描附近的无线热点并记录其ssid/crc以及信道,从而使得airkiss 只用在这几个信道切换抓包. 在我的电脑上打印信息显示你将全部信道都进行了扫描??是不是我下载的代码不是最新的？希望大神可以解释一下。
NL80211_CMD_GET_SCAN sent 28 bytes to the kernel.
Mac Address:[80:89:17:48:ae:96], Channel:[ 1], SSID_CRC:[78], SSID:[TP-LINK_AE96]
Mac Address:[f4:6a:92:26:96:fc], Channel:[ 2], SSID_CRC:[cc], SSID:[zhou'zhou]
Mac Address:[a4:56:02:73:bb:03], Channel:[ 1], SSID_CRC:[40], SSID:[360WiFi-73BB03]
Mac Address:[98:bc:57:46:97:73], Channel:[ 1], SSID_CRC:[ 2], SSID:[ChinaNGB-YDw1ap]
Mac Address:[f8:d1:11:f1:3f:d6], Channel:[ 1], SSID_CRC:[e3], SSID:[manson]
Mac Address:[80:89:17:15:9d:a8], Channel:[ 1], SSID_CRC:[69], SSID:[chinanet]
Mac Address:[30:fc:68:05:35:3a], Channel:[ 1], SSID_CRC:[50], SSID:[maomao]
Mac Address:[24:69:68:01:78:80], Channel:[ 1], SSID_CRC:[3f], SSID:[TP-LINK_7880]
Mac Address:[0c:82:68:95:ff:24], Channel:[ 1], SSID_CRC:[2a], SSID:[TP-LINK_95FF24]
Mac Address:[88:25:93:14:65:ca], Channel:[ 6], SSID_CRC:[b2], SSID:[365/64/602]
Mac Address:[fc:d7:33:32:41:5a], Channel:[ 1], SSID_CRC:[89], SSID:[zhao]
Mac Address:[50:bd:5f:84:6d:d9], Channel:[ 1], SSID_CRC:[e3], SSID:[365/63/602]
Mac Address:[bc:d1:77:3a:06:64], Channel:[13], SSID_CRC:[e7], SSID:[MERCURY_802]

**Comment by evilpan** [comment]
这段打印是wifi_scan扫描周围wifi热点信息的结果,只是测试用的,代码里注释掉了.

**Comment by w450434204** [comment]
我将注释代码wifi_scan(wifi_if, &scan_callback); 打开了。然后运行。报这个错，是什么原因啊
wubiao@wubiao-Rev-1-0:~/桌面/Airkiss-master$ sudo ./airkiss wlp5s0
NL80211_CMD_TRIGGER_SCAN sent 36 bytes to the kernel.
Waiting for scan to complete...
error_handler() called.
WARNING: err has a value of -95.
ERROR: nl_recvmsgs() returned -10 (Operation not supported).
do_scan_trigger() failed with -10.
air_cfg size:128
Airkiss version: V1.2
exec cmd: iw wlp5s0 set channel 2
exec cmd: iw wlp5s0 set channel 3
exec cmd: iw wlp5s0 set channel 4
exec cmd: iw wlp5s0 set channel 5
exec cmd: iw wlp5s0 set channel 6
exec cmd: iw wlp5s0 set channel 7
exec cmd: iw wlp5s0 set channel 8
exec cmd: iw wlp5s0 set channel 9
exec cmd: iw wlp5s0 set channel 10
exec cmd: iw wlp5s0 set channel 11
exec cmd: iw wlp5s0 set channel 12
exec cmd: iw wlp5s0 set channel 13

**Comment by w450434204** [comment]
大神遇到过这种问题吗？

**Comment by w450434204** [comment]
你好。我们的产品是智能摄像头，采用的安卓系统。不知道这类似AirKiss代码能不能运行在安卓系统。。？
   还有你测试扫描wifi热点信息的优化方案。是不是没有加入到gitHub上面这个版本。我电脑上面一直扫描13个信道？谢谢帮忙看下。

**Comment by evilpan** [comment]
扫描wifi热点和切换信道之类的功能是平台相关的, 不同系统都不一样. airkiss本身是应用层的编解码, 和平台没有关系.
