### ISSUE TITLE
我的wifi模块不支持混杂模式，怎么破？求大神指教

### ISSUE THREAD

**Issue by w450434204** [pannzh/Airkiss#8]
我使用的开发板是 RTL8723BU wifi模块组，想实现一键配置的功能。是不是跟新wifi模块的驱动，使其支持混杂模式即可？还是更新开发板

**Comment by evilpan** [comment]
首先确认wifi芯片本身支持混杂模式(一般都是支持的), 然后确定wifi模块(模组)没有切割掉这部分功能,
根据模块的wifi相关驱动关于混杂模式(monitor,promiscuous mode)部分的文档来进行配置,如果没有文档就从驱动的源代码里搜索.

**Comment by w450434204** [comment]
我查看了驱动支持这几种模式。没有promiscuous混杂模式，是不是就不能实现airkiss的功能了？
#define IW_MODE_AUTO    0   // Let the driver decides which AP to join
#define IW_MODE_ADHOC   1   // Single cell network (Ad-Hoc Clients)
#define IW_MODE_INFRA   2   // Multi cell network, roaming, ..
#define IW_MODE_MASTER  3   // Synchronisation master or Access Point
#define IW_MODE_REPEAT  4   // Wireless Repeater (forwarder)
#define IW_MODE_SECOND  5   // Secondary master/repeater (backup)
#define IW_MODE_MONITOR 6   // Passive monitor (listen only)

**Comment by evilpan** [comment]
IW_MODE_MONITOR就是混杂模式

**Comment by w450434204** [comment]
最近一直在研究这项技术，有个问题想再请教你一下。这个是按照UDP广播包的长度定义的应用层传输协议，广播包的内容我们并不关心。如果使用AES对这个系统进行加密，该怎么做？希望能给我提供点思路，我来继续研究。
如果不进行加密的话，别人通过抓包很容易就破解出密码了。

**Comment by w450434204** [comment]
AES是对广播包的长度进行加密吗？

**Comment by evilpan** [comment]
对WIFI密码进行加密然后再通过airkiss传输，这样即便别人抓包并按airkiss协议解析，也只能获得密文信息。 在2016年11月16日 11:01 ，w450434204写道： AES是对广播包的长度进行加密吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by w450434204** [comment]
我通过Wireless-tool工具对无线网卡手动更改模式，
sudo iwconfig wlan0 mode monitor
报错：Error for wireless request "Set Mode" (8B06) :
SET failed on device wlan0 ; Invalid argument.
可能是我的网卡，不支持混杂模式（monitor）。像我这种情况，通过更新驱动能否解决（通过找该芯片支持混杂模式的驱动程序）？PS：我的芯片是RTL8723BU芯片，因为我刚接触这一块，有些不是很懂。
